apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: data-apps-cluster
  region: us-east-1
  tags:
    ProjectName: DataAppOnEKS

nodeGroups:
  - name: prometheus-ng
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 80
    privateNetworking: true