apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: data-apps-cluster
  region: us-east-1
  tags:
    ProjectName: DataAppOnEKS

nodeGroups:
  - name: prometheus-ng
    instanceType: t4g.medium
    desiredCapacity: 1
    volumeSize: 40
    privateNetworking: true