apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: data-apps-cluster
  region: us-east-1
  tags:
    ProjectName: DataAppOnEKS

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
    tags:
      ProjectName: DataAppOnEKS
  - name: fp-data-apps
    selectors:
      - namespace: data-apps
    tags:
      ProjectName: DataAppOnEKS

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]